#!/usr/bin/env python3
"""Export the research checkpoints the demonstration panel offers.

Two model assets are produced from the research runs the adaptation plan names:

``research-cnn-v1``
    ``ResearchNet``'s baseline configuration, which predicts the complete signed
    log2 gain directly.

``research-exif-v1``
    The mean-removed spatial network plus an ordinary-EXIF level estimator.

Both are the same ``DirectGainMapNet`` trunk; only the trained weights and, for
the second, the extra scalar differ.  This script deliberately reuses
``export_onnx`` and ``convert_ncnn`` rather than re-deriving their policies: the
five-plane feature graph, the dynamic-shape export and the pnnx layer allow-list
have all been validated for the incumbent model, and a second implementation of
any of them would be a second place to be wrong.

The EXIF level estimator is flattened into a C++ header with static arrays.  The
fitted object stays the only authority for its own numbers: every exported value
is read out of the trained scikit-learn pipeline, and the companion reference
runner replays the fold's recorded predictions through the flattened form.

    python HyperDR_Model/scripts/export_research_assets.py \\
        --checkpoint .../baseline-f0-s908/best.pt --model-id research-cnn-v1 \\
        --research-run baseline-f0-s908
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import shutil
import sys
import tempfile
from typing import Any

import numpy as np

MODEL_ROOT = Path(__file__).resolve().parents[1]
if str(MODEL_ROOT) not in sys.path:
    sys.path.insert(0, str(MODEL_ROOT))
SCRIPTS = Path(__file__).resolve().parent
if str(SCRIPTS) not in sys.path:
    sys.path.insert(0, str(SCRIPTS))

import torch
from torch import nn
import torch.nn.functional as F

import convert_ncnn
from export_onnx import FEATURE_INPUT_CHANNELS, _check_onnx, _export_graph, _parse_size
from hyperdr_ml.model import MODEL_STRIDE, DirectGainMapNet

DEFAULT_HEIGHT = convert_ncnn.DEFAULT_HEIGHT
DEFAULT_WIDTH = convert_ncnn.DEFAULT_WIDTH
MANIFEST_SCHEMA = 'hyperdr.research-model/v1'

#: The deployment version string both research options carry.  It states the
#: fold and the seed because that is what the asset actually is; it does not
#: claim a five-fold or all-seed average, which this build did not compute.
RESEARCH_DEMO_VERSION = 'research-demo-fold0-seed908/v1'

#: 1e-5 is the offset the research reconstruction adds to the SDR base before
#: the gain is applied (``src/hdr_core.py::reconstruct``).  The incumbent model
#: keeps its own zero offset, so this is a per-model property, not a new global.
RESEARCH_RECONSTRUCTION_OFFSET = {'numerator': 1, 'denominator': 100000}

EXIF_FIELDS = (
    'log2_iso', 'log2_exposure_seconds', 'f_number',
    'exposure_bias_ev', 'focal_length_mm', 'focal_length_35mm',
)

EXIF_DATA_HEADER = '''// Generated by HyperDR_Model/scripts/export_research_assets.py -- do not edit.
//
// The fitted ordinary-EXIF level estimator, flattened into arrays a C++ walker
// can traverse.  Every number below was read out of the trained scikit-learn
// pipeline recorded in the neighbouring manifest; the companion reference
// runner replays this fold's recorded predictions through the same traversal, so
// the flattened form is checked against the fitted object rather than trusted.
//
// `threshold` is the split value on the original feature scale (scikit-learn's
// ``num_threshold``, not the binned one) and ``value`` is the leaf's post
// learning-rate contribution, so no learning rate is applied here.  Both were
// confirmed by comparison, not assumed.

#pragma once

namespace hyperdr {
namespace research_exif_data {

inline constexpr std::size_t kFieldCount = @FIELD_COUNT@;
inline constexpr std::size_t kTreeCount = @TREE_COUNT@;
inline constexpr std::size_t kNodeCount = @NODE_COUNT@;

// Fitted median per field, used only where a field is genuinely absent.  A
// present field is never replaced: exposure bias 0 EV is a real capture value.
inline constexpr double kImputerMedians[kFieldCount] = {
@MEDIANS@
};

inline constexpr double kBaseline = @BASELINE@;

inline constexpr std::size_t kTreeOffsets[kTreeCount + 1] = {
@TREE_OFFSETS@
};

struct Node {
  // Leaf nodes are not followed: `is_leaf` is true and the child indices are -1.
  int feature;
  double threshold;
  int left;
  int right;
  double value;
  bool is_leaf;
  bool missing_go_to_left;
};

inline constexpr Node kNodes[kNodeCount] = {
@NODES@
};

}  // namespace research_exif_data
}  // namespace hyperdr
'''


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with Path(path).open('rb') as source:
        for chunk in iter(lambda: source.read(1 << 20), b''):
            digest.update(chunk)
    return digest.hexdigest()


def _manifest_path(path: Path) -> str:
    resolved = path.resolve()
    try:
        return resolved.relative_to(MODEL_ROOT.parent.resolve()).as_posix()
    except ValueError:
        return str(resolved)


class ResearchFeatureGainMapNet(nn.Module):
    """The trunk's feature-plane graph, matching the incumbent export shape.

    Both research checkpoints keep the same head geometry as production, so the
    export reuses production's reasoning: the five deterministic feature planes
    are built once by the native runtime, and the 2:1 skip is expressed as a
    plain average pool because the documented input contract makes the two equal
    and older pnnx releases cannot lower an adaptive pool with a symbolic
    target shape.
    """

    def __init__(self, model: DirectGainMapNet) -> None:
        super().__init__()
        self.model = model

    def forward(self, features: torch.Tensor) -> torch.Tensor:
        if features.ndim != 4 or features.shape[1] != FEATURE_INPUT_CHANNELS:
            raise ValueError(
                f'ResearchFeatureGainMapNet expects BCHW five-channel features, '
                f'got {tuple(features.shape)}')
        x1 = self.model.stem(features)
        x2 = self.model.stage2(x1)
        x3 = self.model.stage3(x2)
        x4 = self.model.stage4(x3)
        x4 = self.model.context(x4)
        skip = F.avg_pool2d(x3, kernel_size=2, stride=2, ceil_mode=True)
        x4 = x4 + self.model.skip3(skip)
        return self.model.head(x4)


def load_research_trunk(checkpoint: Path) -> tuple[DirectGainMapNet, dict[str, Any]]:
    """Rebuild the trained trunk, strictly.

    ``ResearchNet`` nests the trunk under a ``net.`` prefix.  A checkpoint that
    also carries the feature-conditioned scalar head is rejected: neither
    demonstration model uses it, and loading one while ignoring the other would
    make the exported asset a different model under the same name.
    """
    if not checkpoint.is_file():
        raise SystemExit(f'checkpoint does not exist: {checkpoint}')
    payload = torch.load(checkpoint, map_location='cpu', weights_only=False)
    if not isinstance(payload, dict) or 'state_dict' not in payload:
        raise SystemExit('checkpoint has no state_dict')
    state = payload['state_dict']
    if any(key.startswith('scalar.') for key in state):
        raise SystemExit('checkpoint carries a feature-conditioned scalar head; '
                         'the demonstration models answer from the spatial '
                         'network and, for model 2, the EXIF estimator alone')
    trunk_state = {}
    for key, value in state.items():
        if not key.startswith('net.'):
            raise SystemExit(f'checkpoint parameter outside the trunk: {key}')
        trunk_state[key[len('net.'):]] = value
    config = payload.get('configuration')
    if not isinstance(config, dict):
        raise SystemExit('checkpoint has no model configuration')
    model = DirectGainMapNet(int(config['base_channels']), config['architecture'],
                             'signed_stops_v2')
    try:
        model.load_state_dict(trunk_state, strict=True)
    except (RuntimeError, KeyError) as exc:
        raise SystemExit(f'checkpoint weights do not match DirectGainMapNet: {exc}') from exc
    model.eval()
    model.requires_grad_(False)
    return model, {'configuration': config, 'best_epoch': payload.get('best_epoch'),
                   'feature_mean': payload.get('feature_mean'),
                   'feature_std': payload.get('feature_std')}


def export_spatial_assets(model: DirectGainMapNet, model_id: str, output_dir: Path,
                          pnnx: str | None, height: int, width: int) -> dict[str, Any]:
    graph = ResearchFeatureGainMapNet(model)
    graph.requires_grad_(False)
    onnx_path = output_dir / f'{model_id}.features.onnx'
    _export_graph(graph, onnx_path, input_name='features', output_name='gain_stops',
                  height=height, width=width, batch=1, opset=18, dynamic=True)
    _check_onnx(onnx_path, input_name='features', dynamic=True)
    # `convert_ncnn` names its output after the incumbent model.  Convert in a
    # scratch directory and move the pair in: writing it beside the checked-in
    # assets would overwrite production-v3's param/bin before the rename.
    with tempfile.TemporaryDirectory(prefix='hyperdr-research-ncnn-') as scratch:
        manifest = convert_ncnn.convert_ncnn(
            checkpoint=onnx_path,           # records the ONNX as the conversion source
            output_dir=Path(scratch),
            pnnx=pnnx,
            height=height,
            width=width,
            second_height=None,
            second_width=None,
            source_onnx=onnx_path,
        )
        renamed = {}
        for suffix in ('param', 'bin'):
            generated = Path(scratch) / f'production-v3.ncnn.{suffix}'
            target = output_dir / f'{model_id}.ncnn.{suffix}'
            if not generated.is_file():
                raise SystemExit(f'pnnx produced no {generated.name}')
            shutil.copyfile(generated, target)
            renamed[suffix] = target
    record_path = output_dir / f'{model_id}.ncnn.json'
    manifest['assets']['param']['file'] = _manifest_path(renamed['param'])
    manifest['assets']['param']['sha256'] = _sha256(renamed['param'])
    manifest['assets']['param']['size_bytes'] = renamed['param'].stat().st_size
    manifest['assets']['bin']['file'] = _manifest_path(renamed['bin'])
    manifest['assets']['bin']['sha256'] = _sha256(renamed['bin'])
    manifest['assets']['bin']['size_bytes'] = renamed['bin'].stat().st_size
    manifest['source']['kind'] = 'onnx'
    manifest['source']['file'] = _manifest_path(onnx_path)
    manifest['source']['sha256'] = _sha256(onnx_path)
    manifest.pop('checkpoint', None)
    record_path.write_text(json.dumps(manifest, indent=2) + '\n', encoding='utf-8')
    return {'onnx': onnx_path, 'param': renamed['param'], 'bin': renamed['bin'],
            'ncnn_manifest': record_path, 'ncnn': manifest}


def load_exif_pipeline(exif_json: Path):
    if not exif_json.is_file():
        raise SystemExit(
            f'the EXIF level export is missing: {exif_json}\n'
            'run src/research_model_reference.py in the research workspace first')
    return json.loads(exif_json.read_text(encoding='utf-8'))


def render_exif_data_header(export: dict[str, Any]) -> str:
    trees = export['trees']
    if len(export['imputer_statistics']) != len(EXIF_FIELDS):
        raise SystemExit('the EXIF export does not carry six imputer medians')
    offsets = [0]
    nodes = []
    for tree in trees:
        for index in range(len(tree['feature'])):
            nodes.append(
                '    {{{feature}, {threshold!r}, {left}, {right}, {value!r}, '
                '{is_leaf}, {missing}}},'.format(
                    feature=tree['feature'][index],
                    threshold=float(tree['threshold'][index]),
                    left=tree['left'][index],
                    right=tree['right'][index],
                    value=float(tree['value'][index]),
                    is_leaf='true' if tree['is_leaf'][index] else 'false',
                    missing='true' if tree['missing_go_to_left'][index] else 'false',
                ))
        offsets.append(len(nodes))
    return (EXIF_DATA_HEADER
            .replace('@FIELD_COUNT@', str(len(EXIF_FIELDS)))
            .replace('@TREE_COUNT@', str(len(trees)))
            .replace('@NODE_COUNT@', str(len(nodes)))
            .replace('@MEDIANS@', '\n'.join(f'    {value!r},' for value in export['imputer_statistics']))
            .replace('@BASELINE@', repr(float(export['baseline'])))
            .replace('@TREE_OFFSETS@', ',\n'.join(f'    {value}' for value in offsets))
            .replace('@NODES@', '\n'.join(nodes)))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--checkpoint', required=True, type=Path)
    parser.add_argument('--model-id', required=True,
                        choices=('research-cnn-v1', 'research-exif-v1'))
    parser.add_argument('--ui-name', required=True)
    parser.add_argument('--research-run', required=True)
    parser.add_argument('--fold', type=int, default=0)
    parser.add_argument('--seed', type=int, default=908)
    parser.add_argument('--description', default='')
    parser.add_argument('--fallback-model-id', default='')
    parser.add_argument('--exif-level-export', type=Path,
                        help='flattened estimator produced by the research reference runner')
    parser.add_argument('--exif-data-header', type=Path,
                        help='where to write the generated C++ header')
    parser.add_argument('--output-dir', type=Path,
                        default=MODEL_ROOT / 'models')
    parser.add_argument('--pnnx', help='path to the pinned pnnx converter')
    parser.add_argument('--height', type=lambda v: _parse_size(v, '--height'),
                        default=DEFAULT_HEIGHT)
    parser.add_argument('--width', type=lambda v: _parse_size(v, '--width'),
                        default=DEFAULT_WIDTH)
    args = parser.parse_args(argv)

    args.output_dir.mkdir(parents=True, exist_ok=True)
    model, payload = load_research_trunk(args.checkpoint)
    spatial = export_spatial_assets(model, args.model_id, args.output_dir,
                                    args.pnnx, args.height, args.width)

    manifest: dict[str, Any] = {
        'schema': MANIFEST_SCHEMA,
        'modelId': args.model_id,
        'uiName': args.ui_name,
        'version': RESEARCH_DEMO_VERSION,
        'description': args.description,
        'researchRun': args.research_run,
        'fold': args.fold,
        'seed': args.seed,
        'checkpoint': {
            'file': str(args.checkpoint.resolve()),
            'sha256': _sha256(args.checkpoint),
            'best_epoch': payload.get('best_epoch'),
        },
        'model': {
            'family': 'DirectGainMapNet',
            'base_channels': int(payload['configuration']['base_channels']),
            'architecture': payload['configuration']['architecture'],
            'parameters': sum(parameter.numel() for parameter in model.parameters()),
            'output': 'single-channel raw signed log2 gain in stops',
        },
        'graph': spatial['ncnn']['graph'],
        'tool': {
            'torch': torch.__version__,
            'numpy': np.__version__,
            'pnnx': convert_ncnn.CONVERTER_VERSION,
        },
        'assets': {
            'onnx': {
                'file': _manifest_path(spatial['onnx']),
                'sha256': _sha256(spatial['onnx']),
            },
            'param': spatial['ncnn']['assets']['param'],
            'bin': spatial['ncnn']['assets']['bin'],
        },
        'spatialMeanRemoved': args.model_id == 'research-exif-v1',
        'exif': None,
        'fallbackModelId': args.fallback_model_id,
        'reconstructionOffset': RESEARCH_RECONSTRUCTION_OFFSET,
        'scope': 'isolated fold deployment asset; not a five-fold or all-seed average',
        'inferenceOnly': True,
    }

    if args.model_id == 'research-exif-v1':
        if not args.exif_level_export or not args.exif_data_header:
            raise SystemExit('research-exif-v1 needs --exif-level-export and --exif-data-header')
        export = load_exif_pipeline(args.exif_level_export)
        audit = args.output_dir / f'{args.model_id}.exif-level.json'
        audit.write_text(json.dumps(export, indent=2) + '\n', encoding='utf-8')
        header = args.exif_data_header
        header.parent.mkdir(parents=True, exist_ok=True)
        header.write_text(render_exif_data_header(export), encoding='utf-8')
        manifest['exif'] = {
            'estimator': 'SimpleImputer(median) + HistGradientBoostingRegressor',
            'loss': export['loss'],
            'learningRate': export['learning_rate'],
            'maxDepth': export['max_depth'],
            'maxIter': export['max_iter'],
            'minSamplesLeaf': export['min_samples_leaf'],
            'l2Regularization': export['l2_regularization'],
            'randomState': export['random_state'],
            'fieldOrder': list(EXIF_FIELDS),
            'imputerMedians': export['imputer_statistics'],
            'baseline': export['baseline'],
            'treeCount': len(export['trees']),
            'auditRecord': _manifest_path(audit),
            'generatedHeader': _manifest_path(header),
            'generatedHeaderSha256': _sha256(header),
        }
        manifest['assets']['exifLevel'] = {
            'file': _manifest_path(audit),
            'sha256': _sha256(audit),
        }

    manifest_path = args.output_dir / f'{args.model_id}.manifest.json'
    manifest_path.write_text(json.dumps(manifest, indent=2) + '\n', encoding='utf-8')
    summary = dict(manifest)
    summary['ncnnLayers'] = spatial['ncnn']['layers']
    print(json.dumps({k: v for k, v in summary.items()
                      if k not in ('graph',)}, indent=2, ensure_ascii=False))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
