#include "hyperdr/app/schema.hpp"

#include "hyperdr/foundation/file_io.hpp"
#include "hyperdr/foundation/version.hpp"

#include <algorithm>
#include <array>
#include <cmath>
#include <charconv>
#include <stdexcept>

namespace hyperdr {
namespace {

constexpr std::array<std::string_view, 6> kEncodingChoices{
    "adaptive", "ultrahdr", "pq", "hlg", "avif-pq", "avif-hlg"};
constexpr std::array<std::string_view, 1> kLookChoices{"photographic"};
constexpr std::array<std::string_view, 4> kHighlightRecoveryChoices{
    "blend", "reconstruct", "clip", "unclip"};

// --- accessors -------------------------------------------------------------
// Each pair is the only place that knows where a setting lives in
// ConvertOptions. Written out rather than generated by macro so that a reader
// can see exactly what a flag touches.

float as_float(const json::Value& value) { return static_cast<float>(value.number()); }

void apply_encoding(ConvertOptions& o, const json::Value& v) {
  const auto encoding = hdr_encoding_from_name(v.string());
  if (!encoding) throw std::invalid_argument("unknown encoding: " + v.string());
  o.encoding = *encoding;
}
json::Value read_encoding(const ConvertOptions& o) {
  return json::Value::from_string(hdr_encoding_name(o.encoding));
}

void apply_look(ConvertOptions& o, const json::Value& v) {
  const auto mode = look_mode_from_name(v.string());
  if (!mode) throw std::invalid_argument("unknown look: " + v.string());
  o.gain.look.mode = *mode;
}
json::Value read_look(const ConvertOptions& o) {
  return json::Value::from_string(look_mode_name(o.gain.look.mode));
}

void apply_highlight_recovery(ConvertOptions& o, const json::Value& v) {
  const auto mode = highlight_recovery_from_name(v.string());
  if (!mode) throw std::invalid_argument("unknown highlight recovery: " + v.string());
  o.raw.highlight_recovery = *mode;
}
json::Value read_highlight_recovery(const ConvertOptions& o) {
  return json::Value::from_string(highlight_recovery_name(o.raw.highlight_recovery));
}

// "auto" or an explicit value, for the two settings that accept both. The flag
// and the automatic bit are set together so they can never disagree.
void apply_exposure(ConvertOptions& o, const json::Value& v) {
  o.gain.auto_exposure = v.is_string();
  if (!o.gain.auto_exposure) o.gain.exposure_ev = as_float(v);
}
json::Value read_exposure(const ConvertOptions& o) {
  return o.gain.auto_exposure ? json::Value::from_string("auto")
                              : json::Value::from_number(o.gain.exposure_ev);
}
void apply_headroom(ConvertOptions& o, const json::Value& v) {
  o.gain.auto_headroom = v.is_string();
  if (!o.gain.auto_headroom) o.gain.headroom_stops = as_float(v);
}
json::Value read_headroom(const ConvertOptions& o) {
  return o.gain.auto_headroom ? json::Value::from_string("auto")
                              : json::Value::from_number(o.gain.headroom_stops);
}

const std::array<Setting, 26>& table() {
  static const std::array<Setting, 26> kSettings{{
      {"encoding", "--encoding", SettingKind::kEnum, 0, 0, kEncodingChoices,
       "adaptive|ultrahdr|pq|hlg|avif-pq|avif-hlg", "Output representation", false,
       true,
       [](std::string_view name) { return hdr_encoding_from_name(name).has_value(); },
       apply_encoding, read_encoding},
      {"look", "--look", SettingKind::kEnum, 0, 0, kLookChoices,
       "photographic",
       "Renderer", false, true, nullptr, apply_look,
       read_look},
      {"highlight_recovery", "--highlight-recovery", SettingKind::kEnum, 0, 0,
       kHighlightRecoveryChoices, "blend|reconstruct|clip|unclip",
       "RAW clipped-highlight handling", false, true, nullptr,
       apply_highlight_recovery, read_highlight_recovery},
      {"raw_gain", "--raw-gain", SettingKind::kNumber, 0.125, 64.0, {},
       "<0.125..64>", "Sensor-domain RAW digital gain", false, true, nullptr,
       [](ConvertOptions& o, const json::Value& v) {
         o.raw.digital_gain = as_float(v);
       },
       [](const ConvertOptions& o) {
         return json::Value::from_number(o.raw.digital_gain);
       }},
      {"raw_auto_bad_pixels", "--raw-auto-bad-pixels", SettingKind::kBoolean,
       0, 0, {}, {}, "Conservative RAW hot/dead pixel correction", false, true,
       nullptr,
       [](ConvertOptions& o, const json::Value& v) {
         o.raw.auto_bad_pixel_correction = v.boolean();
       },
       [](const ConvertOptions& o) {
         return json::Value::from_bool(o.raw.auto_bad_pixel_correction);
       }},

      {"contrast", "--contrast", SettingKind::kNumber, 0.80, 1.35, {},
       "<0.80..1.35>", "Photographic mid-tone slope", false, true, nullptr,
       [](ConvertOptions& o, const json::Value& v) { o.gain.look.contrast = as_float(v); },
       [](const ConvertOptions& o) { return json::Value::from_number(o.gain.look.contrast); }},
      {"vibrance", "--vibrance", SettingKind::kNumber, -0.50, 0.50, {},
       "<-0.50..0.50>", "Photographic saturation of unsaturated colours", false, true, nullptr,
       [](ConvertOptions& o, const json::Value& v) { o.gain.look.vibrance = as_float(v); },
       [](const ConvertOptions& o) { return json::Value::from_number(o.gain.look.vibrance); }},
      {"pop", "--pop", SettingKind::kNumber, 0.0, 1.0, {}, "<0..1>",
       "Photographic EDR strength boost", false, true, nullptr,
       [](ConvertOptions& o, const json::Value& v) { o.gain.look.pop = as_float(v); },
       [](const ConvertOptions& o) { return json::Value::from_number(o.gain.look.pop); }},
      {"headroom_max", "--headroom-max", SettingKind::kNumber, 0.0, 4.0, {},
       "<0..4>", "Photographic auto-headroom ceiling, in stops", false, true, nullptr,
       [](ConvertOptions& o, const json::Value& v) { o.gain.look.headroom_max_stops = as_float(v); },
       [](const ConvertOptions& o) { return json::Value::from_number(o.gain.look.headroom_max_stops); }},
      {"expansion_start", "--expansion-start", SettingKind::kNumber, 0.18, 0.75, {},
       "<0.18..0.75>", "Linear SDR level where HDR expansion begins", false, true, nullptr,
       [](ConvertOptions& o, const json::Value& v) { o.gain.look.shoulder_start = as_float(v); },
       [](const ConvertOptions& o) { return json::Value::from_number(o.gain.look.shoulder_start); }},
      {"area_coverage", "--area-coverage", SettingKind::kNumber, 0.0, 1.0, {},
       "<0..1>", "Bright-region coverage, local highlights to broad tones", false, true, nullptr,
       [](ConvertOptions& o, const json::Value& v) { o.gain.look.diffuse_gain_floor = as_float(v); },
       [](const ConvertOptions& o) { return json::Value::from_number(o.gain.look.diffuse_gain_floor); }},
      {"gain_strength", "--gain-strength", SettingKind::kNumber, 0.0, 2.0, {},
       "<0..2>", "Gain-map scale; photographic values above 1 are capped", false, true, nullptr,
       [](ConvertOptions& o, const json::Value& v) { o.gain.gain_strength = as_float(v); },
       [](const ConvertOptions& o) { return json::Value::from_number(o.gain.gain_strength); }},
      {"exposure_bias", "--exposure-bias", SettingKind::kNumber, 0.0, 2.0, {},
       "<0..2>", "Creative offset applied after exposure selection", false, true, nullptr,
       [](ConvertOptions& o, const json::Value& v) { o.gain.exposure_bias_ev = as_float(v); },
       [](const ConvertOptions& o) { return json::Value::from_number(o.gain.exposure_bias_ev); }},

      {"exposure", "--exposure", SettingKind::kAutoOrNumber, -10.0, 10.0, {},
       "auto|<EV>", "Exposure selection", false, true, nullptr, apply_exposure,
       read_exposure},
      {"headroom", "--headroom", SettingKind::kAutoOrNumber, 0.0, 4.0, {},
       "auto|<stops>", "HDR headroom target", false, true, nullptr, apply_headroom,
       read_headroom},

      {"quality", "--quality", SettingKind::kInteger, 0, 100, {}, "<0..100>",
       "Encoder quality", false, true, nullptr,
       [](ConvertOptions& o, const json::Value& v) { o.quality = static_cast<int>(v.number()); },
       [](const ConvertOptions& o) { return json::Value::from_number(o.quality); }},
      {"depth", "--depth", SettingKind::kInteger, 8, 10, {}, "<8|10>",
       "HEIC base depth; Ultra HDR JPEG requires 8", false, true, nullptr,
       [](ConvertOptions& o, const json::Value& v) {
         const auto depth = static_cast<int>(v.number());
         if (depth != 8 && depth != 10) throw std::invalid_argument("depth must be 8 or 10");
         o.depth = depth;
       },
       [](const ConvertOptions& o) { return json::Value::from_number(o.depth); }},
      {"preview_max_edge", "--preview-max-edge", SettingKind::kInteger, 0, 8192, {},
       "<pixels>", "Bound resolution before look processing", false, true, nullptr,
       [](ConvertOptions& o, const json::Value& v) {
         o.preview_max_edge = static_cast<std::uint32_t>(v.number());
       },
       [](const ConvertOptions& o) { return json::Value::from_number(o.preview_max_edge); }},

      {"recursive", "--recursive", SettingKind::kBoolean, 0, 0, {}, {},
       "Scan subdirectories", false, false, nullptr,
       [](ConvertOptions& o, const json::Value& v) { o.recursive = v.boolean(); },
       [](const ConvertOptions& o) { return json::Value::from_bool(o.recursive); }},
      {"verify_output", "--no-verify", SettingKind::kBoolean, 0, 0, {}, {},
       "Skip post-encode decode verification", true, false, nullptr,
       [](ConvertOptions& o, const json::Value& v) { o.verify_output = v.boolean(); },
       [](const ConvertOptions& o) { return json::Value::from_bool(o.verify_output); }},
      {"overwrite", "--overwrite", SettingKind::kBoolean, 0, 0, {}, {},
       "Replace existing outputs", false, false, nullptr,
       [](ConvertOptions& o, const json::Value& v) { o.overwrite = v.boolean(); },
       [](const ConvertOptions& o) { return json::Value::from_bool(o.overwrite); }},
      {"skip_existing", "--skip-existing", SettingKind::kBoolean, 0, 0, {}, {},
       "Skip outputs already rendered from the same input and settings", false, false, nullptr,
       [](ConvertOptions& o, const json::Value& v) { o.skip_existing = v.boolean(); },
       [](const ConvertOptions& o) { return json::Value::from_bool(o.skip_existing); }},
      // Internal: not settable, but part of the rendered bytes, so a resumable
      // batch has to notice if a future version changes one.
      {"half_size", {}, SettingKind::kBoolean, 0, 0, {}, {},
       "RAW half-size demosaic (set by the preview path)", false, true, nullptr,
       nullptr,
       [](const ConvertOptions& o) { return json::Value::from_bool(o.raw.half_size); }},
      {"toe_end", {}, SettingKind::kNumber, 0.0, 1.0, {}, {},
       "Scene luminance where the toe ends", false, true, nullptr, nullptr,
       [](const ConvertOptions& o) { return json::Value::from_number(o.gain.look.toe_end); }},
      {"toe_output_ratio", {}, SettingKind::kNumber, 0.0, 1.0, {}, {},
       "Toe output as a fraction of its linear extension", false, true, nullptr,
       nullptr,
       [](const ConvertOptions& o) { return json::Value::from_number(o.gain.look.toe_output_ratio); }},
      {"positive_exposure_limit", {}, SettingKind::kNumber, 0.0, 8.0, {}, {},
       "Exposure ceiling for low-light captures, in stops", false, true, nullptr,
       nullptr,
       [](const ConvertOptions& o) {
         return json::Value::from_number(o.gain.look.positive_exposure_limit_ev);
       }},
  }};
  return kSettings;
}

[[noreturn]] void range_error(const Setting& setting) {
  throw std::invalid_argument(
      std::string(setting.key) + " must be in [" + json::number_text(setting.minimum) +
      ", " + json::number_text(setting.maximum) + "]");
}

[[noreturn]] void type_error(const Setting& setting, std::string_view expected) {
  throw std::invalid_argument(std::string(setting.key) + " must be " +
                             std::string(expected));
}

double parse_number(const Setting& setting, std::string_view text) {
  // std::from_chars for floating point is unimplemented in some standard
  // libraries this project builds against, so the text goes through stod with
  // an explicit "consumed everything" check.
  try {
    std::size_t used = 0;
    const double value = std::stod(std::string(text), &used);
    if (used != text.size() || !std::isfinite(value)) throw std::invalid_argument("bad");
    return value;
  } catch (const std::exception&) {
    throw std::invalid_argument("invalid " + std::string(setting.key) + ": " +
                                std::string(text));
  }
}

}  // namespace

std::span<const Setting> settings() { return table(); }

const Setting* find_setting_by_key(std::string_view key) {
  for (const auto& setting : table()) {
    if (setting.key == key) return &setting;
  }
  return nullptr;
}

const Setting* find_setting_by_flag(std::string_view flag) {
  if (flag.empty()) return nullptr;
  for (const auto& setting : table()) {
    if (setting.flag == flag) return &setting;
  }
  return nullptr;
}

void validate_setting_value(const Setting& setting, const json::Value& value) {
  switch (setting.kind) {
    case SettingKind::kEnum: {
      if (!value.is_string()) type_error(setting, "a name");
      const bool known =
          setting.accepts_name != nullptr
              ? setting.accepts_name(value.string())
              : std::find(setting.choices.begin(), setting.choices.end(),
                          value.string()) != setting.choices.end();
      if (!known) {
        std::string expected;
        for (const auto& choice : setting.choices) {
          if (!expected.empty()) expected += ", ";
          expected += choice;
        }
        throw std::invalid_argument("invalid " + std::string(setting.key) + ": \"" +
                                   value.string() + "\" (expected one of " +
                                   expected + ")");
      }
      return;
    }
    case SettingKind::kBoolean:
      if (!value.is_bool()) type_error(setting, "true or false");
      return;
    case SettingKind::kNumber:
    case SettingKind::kInteger:
      if (!value.is_number()) type_error(setting, "a number");
      break;
    case SettingKind::kAutoOrNumber:
      if (value.is_string()) {
        if (value.string() != "auto") type_error(setting, R"("auto" or a number)");
        return;
      }
      if (!value.is_number()) type_error(setting, R"("auto" or a number)");
      break;
  }
  const double number = value.number();
  if (!std::isfinite(number) || number < setting.minimum || number > setting.maximum) {
    range_error(setting);
  }
  if (setting.kind == SettingKind::kInteger && number != std::floor(number)) {
    type_error(setting, "a whole number");
  }
}

json::Value parse_setting_text(const Setting& setting, std::string_view text) {
  json::Value value;
  switch (setting.kind) {
    case SettingKind::kEnum:
      value = json::Value::from_string(std::string(text));
      break;
    case SettingKind::kBoolean:
      // A boolean flag carries no value on the command line; its presence is
      // the value, inverted for `--no-verify`.
      value = json::Value::from_bool(!setting.flag_sets_false);
      break;
    case SettingKind::kNumber:
    case SettingKind::kInteger:
      value = json::Value::from_number(parse_number(setting, text));
      break;
    case SettingKind::kAutoOrNumber:
      value = text == "auto" ? json::Value::from_string("auto")
                             : json::Value::from_number(parse_number(setting, text));
      break;
  }
  validate_setting_value(setting, value);
  return value;
}

void apply_preset_document(const json::Value& document, ConvertOptions& options) {
  if (!document.is_object()) throw std::invalid_argument("preset must be a JSON object");
  for (const auto& [key, value] : document.members()) {
    // A report file also has a "schema" member; accepting and ignoring it turns
    // "you handed me a report" into a clear message rather than an unknown-key one.
    if (key == "schema") continue;
    const Setting* setting = find_setting_by_key(key);
    if (setting == nullptr || !setting->presetable() || setting->apply == nullptr) {
      throw std::invalid_argument("unknown preset key: \"" + key + "\"");
    }
    validate_setting_value(*setting, value);
    setting->apply(options, value);
  }
}

std::string settings_usage_text() {
  std::string out;
  for (const auto& setting : table()) {
    if (!setting.presetable()) continue;
    std::string left(setting.flag);
    if (setting.kind != SettingKind::kBoolean) {
      left += ' ';
      left += setting.value_label;
    }
    // Two columns, wide enough for the longest flag plus its placeholder.
    if (left.size() < 34) left.append(34 - left.size(), ' ');
    out += "  " + left + " " + std::string(setting.help) + "\n";
  }
  return out;
}

std::string schema_json() {
  const ConvertOptions defaults;
  json::Writer writer(json::Writer::Style::kIndented);
  writer.begin_object().member("schema", 1).member("tool", kVersion).begin_array("settings");
  for (const auto& setting : table()) {
    if (!setting.presetable()) continue;
    writer.begin_object().member("key", setting.key).member("flag", setting.flag);
    switch (setting.kind) {
      case SettingKind::kEnum: writer.member("kind", "enum"); break;
      case SettingKind::kNumber: writer.member("kind", "number"); break;
      case SettingKind::kInteger: writer.member("kind", "integer"); break;
      case SettingKind::kBoolean: writer.member("kind", "boolean"); break;
      case SettingKind::kAutoOrNumber: writer.member("kind", "auto_or_number"); break;
    }
    if (setting.kind == SettingKind::kEnum) {
      writer.begin_array("choices");
      for (const auto& choice : setting.choices) writer.element(choice);
      writer.end_array();
    } else if (setting.kind != SettingKind::kBoolean) {
      writer.member("minimum", setting.minimum).member("maximum", setting.maximum);
    }
    if (setting.kind == SettingKind::kBoolean) {
      writer.member("flag_sets_false", setting.flag_sets_false);
    }
    writer.member("affects_output_bytes", setting.affects_output_bytes)
        .member("help", setting.help);
    const json::Value value = setting.read(defaults);
    if (value.is_string()) writer.member("default", value.string());
    else if (value.is_bool()) writer.member("default", value.boolean());
    else writer.member("default", value.number());
    writer.end_object();
  }
  return writer.end_array().end_object().take() + "\n";
}

}  // namespace hyperdr
